### ISSUE TITLE
Subscriptions are ignored when running app via <head> tag

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#62]
Relevant code https://github.com/hyperapp/hyperapp/blob/master/app.js#L81.

Ping @dodekeract.

#### Resources
* http://stackoverflow.com/questions/16643232/how-to-know-if-document-has-loaded

**Comment by jbucaran** [comment]
Something like this would do.

```js
	ready(function () {
		for (var sub in subs) {
			subs[sub](model, msg, hooks.onError)
		}
	})

	function ready(cb) {
		document.readyState === "complete"
			? cb()
			: document.addEventListener("DOMContentLoaded", cb)
	}
```

**Comment by jbucaran** [comment]
> @dodekeract Is there any reason why we can't just treat "render app()" as the first sub?

Interesting question. That way you wouldn't even need to detect DOMContentLoaded yourself.

**Comment by jbucaran** [comment]
I think it's not the right thing to do, because that smells like [magic](https://en.wikipedia.org/wiki/Magic_(programming)).

**Comment by rbiggs** [comment]
Document ready, etc. Ugh! It's complicated. Here's what I came up with to deal with the mess. Handles situations where the document is already ready for different browsers since they can't decide on how to let us now this so unimportant and insignificant condition ;-P:

```
function ready(callback) {
  const readyRE = /complete|loaded|interactive/;

  if (readyRE.test(document.readyState) && document.body) {
    callback.call(callback);
  } else {
    document.addEventListener("DOMContentLoaded", function() {
      return callback.call(callback);
    });
  }
}
```

**Comment by tunnckoCore** [comment]
I don't think it should be in the app/framework side. I believe it would be better to expose `.start` method or just such. So user will "start" the app when he want. That's why I exposed `.start()` in [gibon](http://ghub.io/gibon) router - before calling start it does not listen on any events.

**Comment by jbucaran** [comment]
I agree with @tunnckoCore. Instead of a clunky .start() method, however, you already have a function, `app`, which you can call when you are ready.

Thanks @rbiggs! I'm almost done implementing this.

I'll push in a while with a few other minor improvements.

**Comment by dodekeract** [comment]
@tunnckoCore Having a `.start()` method would just lead to my initial question once again. Which event should that be attached to so that `subs` don't break?

**Comment by jbucaran** [comment]
Hi @dodekeract, this is now fixed in the master branch. Subscriptions (**not subs** anymore) will work even when you run `app(...)` inside DOMContentLoaded.

See https://github.com/hyperapp/hyperapp/blob/master/app.js#L8

**Comment by dodekeract** [comment]
@jbucaran thanks, will open another issue if it doesn't work, but looks good.

**Comment by jbucaran** [comment]
@dodekeract Thanks, I'll keep this open. Test it out and please close when, and if, the previous behavior is fixed.

**Comment by dodekeract** [comment]
@jbucaran I can still reproduce this when using `yarn add git+ssh://git@github.com/hyperapp/hyperapp.git`. `node_modules/hyperapp/app.js` also seems to be the current version.

**Comment by jbucaran** [comment]
@dodekeract You're using the wrong bundle in broken.html, it should be bundle.onload.js.

**Comment by jbucaran** [comment]
|  Not broken.html | Not broken.root.html  |
|---|---|
|  ![screen shot 2017-02-09 at 14 31 50](https://cloud.githubusercontent.com/assets/56996/22770600/030201d4-eed5-11e6-8874-f837ec10a3e9.png) |  ![screen shot 2017-02-09 at 14 32 02](https://cloud.githubusercontent.com/assets/56996/22770601/0305f8d4-eed5-11e6-9ae5-83c387065593.png)
 |

@dodekeract

**Comment by dodekeract** [comment]
@jbucaran Of course I'm using `index.js` in both `index.html` and `broken.html`. That's why one is called broken, because it doesn't reliably work with the normal way to include hyperapp.

Only thing I'll change is that `onload.html` should actually have the script in the head, but that doesn't make any difference.

`index.js` -> `index.html` + `broken.html`  
`index.root.js` -> `broken.root.html`  
`index.onload.js` -> `onload.html`

**Comment by jbucaran** [comment]
@dodekeract Why?

**Comment by dodekeract** [comment]
@jbucaran Because the repo demonstrates the different ways to include hyperapp and every html called `broken` is a demo of a way that doesn't work?

**Comment by jbucaran** [comment]
In that case, the title of this issue is misleading. Subscriptions now work when running the app via `<head>`.

**Comment by dodekeract** [comment]
@jbucaran It still crashes in both `broken.html` and `broken.root.html`.

**Comment by jbucaran** [comment]
@dodekeract Are you using `window.addEventListener("load")` or `document.addEventListener("DOMContentLoaded")` to run the app?

**Comment by dodekeract** [comment]
@jbucaran In `onload.html` I'm using that, yes. That's the point of having multiple slightly different files.

Is it **required** now to use `window.addEventListener` to make this work?

**Comment by jbucaran** [comment]
@dodekeract We now understand each other.

At the moment, yes, it's required because when embedding hyperapp in the `<head>`, hyperapp's render/patch functions will fail.

The question is, should we make hyperapp aware of this out of the box?

@tunnckoCore @terkelg @tzellman

**Comment by dodekeract** [comment]
@jbucaran No matter what the decision is, the behavior should be documented. 🙂

**Comment by dodekeract** [comment]
@jbucaran Issue can be closed then. I'd suggest to open a new one with docs/question if this should work without `window.addEventListener` or not.

**Comment by jbucaran** [comment]
@dodekeract That sounds like the right thing to do. Can you take care of opening it?
