### ISSUE TITLE
{...props} causes TypeError

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#93]
This code crashes due to `children` being assigned to the `<div>`. I think it works in React. I'm assuming React doesn't pass `children` when it's empty. Not sure though.

`TypeError: Attempted to assign to readonly property.`

`TypeError: undefined is not an object (evaluating 'e.childNodes')`

---

## Broken Code

```javascript
export default ({...props}) =>
	<div {...props}>Example!</div>
```

## Working Code
```javascript
export default ({children, ...props}) =>
	<div {...props}>Example!</div>
```

**Comment by jbucaran** [comment]
@selfup Are you familiar with React or what they do / how it works in this situation?

**Comment by lukeed** [comment]
In Inferno & Preact, `children` gets stripped from the `props` object.

**Comment by tunnckoCore** [comment]
I believe it would be better to always defaults it to empty array, so no errors would happen.

**Comment by dodekeract** [comment]
@tunnckoCore shouldn't that actually cause the issue? 🙂

**Comment by jbucaran** [comment]
The relevant code is here btw: 

* https://github.com/hyperapp/hyperapp/blob/master/src/h.js#L12

**Comment by selfup** [comment]
Yes because it magically passes `e` 😂 

Glad you all figured it out!

**Comment by jbucaran** [comment]
So, in Inferno and Preact, children is removed from props? What about react?

**Comment by selfup** [comment]
With React it's still in there if there are children as the example above ^ ^

**Comment by jbucaran** [comment]
@dodekeract 

Component functions only receive a single `data` (props) argument, why then:

```jsx
export default ({children, ...props}) =>
	<div {...props}>Example!</div>
```

I think I'll need an example I can actually run in order to figure this out.

**Comment by tunnckoCore** [comment]
@dodekeract don't think so

@jbucaran same here, i can't get what can be the reason too. With or without `children`, it not make sense to fail.

**Comment by jbucaran** [comment]
@dodekeract Fixed in https://github.com/hyperapp/hyperapp/commit/7a60a8f18163c31ec74c174c18337b7a31ae2dfb

Please check 🙏

**Comment by dodekeract** [comment]
@jbucaran I just re-read your comment from 2 days ago.

I think you're not that familiar with the object spread syntax, let me explain.

`{children, ...props}` does the following:

1. extract children from the properties.
2. extract all other properties into props.

The bug was caused because `children` was passed into the `<div>`, which apparently is (or was) illegal in hyperapp.

**Comment by jbucaran** [comment]
@dodekeract Can you confirm that the bug you were having was fixed?

**Comment by dodekeract** [comment]
@jbucaran I will later today.

**Comment by jbucaran** [comment]
@dodekeract Please do 🙏 and thanks.

**Comment by dodekeract** [comment]
I can still reproduce this in `0.4.1`.

[Working](http://codepen.io/anon/pen/vgwZWx?editors=0010)
[Broken](http://codepen.io/anon/pen/BpeZmY?editors=0010)

**Comment by dodekeract** [comment]
@jbucaran Please re-open.

**Comment by jbucaran** [comment]
@dodekeract Okay, two things we can do:

1. Strip children from props _a-la_ Preat/Inferno (break the API with it) and go with `(props, children)`.
2. Skip children magically when setting element data in `createElementFrom(node)`. 

Both are simple to do, simplest is 1, but 2 is frictionless and Just Works™.

**Comment by lukeed** [comment]
I'd go with option 1. Especially since you're not shipping hyperx anymore, and instead welcoming any plugin-renderers, they nearly all expect children to be its own parameter.

**Comment by lukeed** [comment]
Then again, I'm not familiar enough with hyperapp and the implications this will entail.

**Comment by tunnckoCore** [comment]
React compat should not be included. It should be easy to do `hyperapp-compat` or something like that, some wrappers and etc. Like inferno has `inferno-compat`. So yea, we should not care about react. We are not react and we can't do much things that react can do (maybe? i'm almost sure).

As about `(props, children)` it is totally correct btw. Because transpiled JSX never sets children to props. I faced that yesterday playing with `mich-h` and jsx.

So this is perfectly fine

```js
  if (typeof selector === 'function') {
    return selector(node.properties, node.children)
  }
```

**Comment by tunnckoCore** [comment]
Another interesting thing that passing children to props was that you can use such thing

```js
var Foo = ({ name, children }) => <div>
  <h1>{ name }</h1>
  <p>{children}</p>
</div>

var link = <a href="#">Hello World</a>
var tree = <Foo name="Charlike" children={ link } />
```
instead of the link inside the Foo tag

```js
var link = <a href="#">Hello World</a>
var tree = <Foo name="Charlike">{ link }</Foo>
```
